<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="9.0.4" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.11.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Library.Claim\Library.Claim.csproj" />
    <ProjectReference Include="..\..\Library.Infrastructure\Library.Infrastructure.csproj" />
    <ProjectReference Include="..\Account.Domain\Account.Domain.csproj" />
  </ItemGroup>

</Project>
